/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BarChart: typeof import('./components/charts/BarChart.vue')['default']
    LineChart: typeof import('./components/charts/LineChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiBadge: typeof import('./components/ui/UiBadge.vue')['default']
    UiButton: typeof import('./components/ui/UiButton.vue')['default']
    UiCard: typeof import('./components/ui/UiCard.vue')['default']
    UiInput: typeof import('./components/ui/UiInput.vue')['default']
    UiModal: typeof import('./components/ui/UiModal.vue')['default']
    UiSwitch: typeof import('./components/ui/UiSwitch.vue')['default']
  }
}
